version: "3.8"

services:
  api:
    build:
      target: dev
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
  nginx:
    build:
      target: dev
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - workflow-postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTgRES_USER: postgres
      POSTGRES_DB: workflow

volumes:
  workflow-postgres-data:

